apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete
  labels:
    app: complete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete
  template:
    metadata:
      labels:
        app: complete
    spec:
      containers:
        - name: complete
          image: username/complete:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5